project:
  type: website

website:
  title: "Aston Zhang"
  navbar:
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - papers.qmd
  twitter-card: true
  google-analytics: "UA-27909669-4"

format:
  html:
    theme: yeti
    css: styles.css
    toc: false
    toc-title: .



